### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by voischev**

### CODE REVIEW

**Comment by tadatuta** [comment]
@voischev can you please provide some description for this PR?

**Comment by tadatuta** [comment]
and shouldn't it be rebased on https://github.com/gulp-bem/gulp-eval/pull/1/files ?

**Comment by tadatuta** [comment]
cc @zxqfox

**Comment by voischev** [comment]
it is a magic of @zxqfox! ;)

**Comment by Yeti-or** [comment]
@zxqfox I've rebased this upon https://github.com/gulp-bem/gulp-eval/pull/4 and this one is falling: https://github.com/gulp-bem/gulp-eval/pull/4/files#diff-c1129c8b045390789fa8ff62f2c6b4a9R34

**Comment by qfox** [comment]
It's an 

**Pull request merged**
